app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime




class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Blog(db.Model):
    '''
    Class blog that hold all blog data
    '''
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    content = db.Column(db.String(), index=True, nullable=False)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.String)
    comments = db.relationship('Comment', backref='pitch', lazy='dynamic')


    @classmethod
    def get_blogs(cls, id):
        blogs = Blog.query.order_by(blog_id=id).desc().all()
        return blogs

    def get_post_comments(self):
        return Comment.query.filter_by(blog_id=self.id)

    def __repr__(self):
        return f'Blog {self.content}'


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'), nullable=False)
    description = db.Column(db.Text)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    def delete_comment(self):
      '''
      Deletes and commits comment instance from database
      db.session.add(comment)
      db.session.commit()
      '''
      db.session.delete(self)
      db.session.commit()

    def __repr__(self):
      return f"Comment('{self.comment}')"


@login_manager.user_loader
def load_user(user_id):
   return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from app.models import User, Blog, Comment
from wtforms.validators import Required,Email,EqualTo
from wtforms import StringField, PasswordField, SubmitField, ValidationError, BooleanField, RadioField, TextAreaField, IntegerField, SelectField


class Blogform(FlaskForm):
    '''
    Blog post form.
    '''
    title = StringField('Title ')
    content = TextAreaField('Blog Content')
    submit = SubmitField('Publish')


class Commentform(FlaskForm):
    '''
    Comment form.
    '''
    name = StringField('Name', validators=[Required()])
    description = TextAreaField('Add comment', validators=[Required()])
    submit = SubmitField()


class UpdateForm(FlaskForm):
    title = StringField('Title for you Blog', validators=[Required()])
    content= TextAreaField('Blog Content', validators=[Required()])
    submit = SubmitField('Edit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


photos = UploadSet('photos',IMAGES)
bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()


def create_app(config_name):
    # Initialising application
    app = Flask (__name__)

    # Creating app configuration
    app.config.from_object(config_options[config_name])


    # Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)



     # configure UploadSet
    configure_uploads(app,photos)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required,current_user
from ..models import User,Blog,Comment
import os
import requests
import json
# from flask.views import View, MethodView
from .. import db, photos
from .forms import Blogform,Commentform,UpdateForm
from . import main
from datetime import datetime



#views
@main.route ('/')
def index():
    '''
    View root page funct that returns the index page and its data
    '''
    random = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()

    return render_template('index.html', random = random)


@main.route('/posts')
def blog():
    blogs = Blog.query.order_by(Blog.date_posted.desc())
    return render_template('posts.html', blogs=blogs)


@main.route('/blogs/<int:blog_id>',methods = ["GET","POST"])
def view_blog(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first()  
    random = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()

    form = Commentform()
    if form.validate_on_submit():
        name = form.name.data
        content = form.content.data
        new_comment = Comment(name=name, content=content,blog_id=blog.id)
        new_comment.save_comment()
        return redirect(url_for('main.view_blog', blog_id=blog.id))
    comments = Comment.query.filter_by(blog_id=blog.id)

    return render_template("blogs.html", form=form, blog=blog, comments=comments, random = random)

@main.route('/blogs/new/', methods=['GET', 'POST'])
@login_required
def new_blog():
    form = Blogform()
    if form.validate_on_submit():
        content = form.content.data
        title = form.title.data
        owner_id = current_user
        date_posted = str(datetime.now())
        print(current_user._get_current_object().id)
        new_blog = Blog(owner_id=current_user._get_current_object().id, title=title, content=content,
                          date_posted=date_posted)
        db.session.add(new_blog)
        db.session.commit()
        # flash('New blog post created','success')

        return redirect(url_for('main.blog'))
    return render_template('new.html', form=form)


@main.route("/delete/<blog_id>",methods = ['GET','POST'])
def delete(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first()
    db.session.delete(blog)
    db.session.commit()

    return redirect(url_for('main.blog'))


@main.route("/update/<blog_id>", methods= ['GET', 'POST'])
@login_required
def update_blog(blog_id):
    blog = Blog.query.filter_by(id = blog_id).first()
    form = UpdateForm()
    if form.validate_on_submit():
        blog.title = form.title.data
        blog.content = form.content.data
        db.session.commit()
        return redirect(url_for('main.blog'))
    elif request.method == 'GET':
        form.title.data = blog.title
        form.content.data = blog.content


    return render_template('new.html', form=form)


@main.route('/<int:blog_id>/delete comments')
@login_required
def delete_comment(blog_id):
    comment = Comment.query.filter_by(blog_id=blog_id).first()
    blog_id = comment.blog_id

    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('main.view_blog', blog_id=blog_id))




@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/blogs.html
<body>
    {% extends "base.html" %}
    {% import "bootstrap/wtf.html" as wtf%}
    <!-- Styles block -->

    {% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    {% endblock %}


    {% block content%}
    <div class="container">
        <div class="row">

            <div class="col col-md-9">


                <div class="panel panel_default">

                    <div class="panel-heading">
                        <h1 id="title">{{blog.title}}</h1>

                    </div>

                    <div class="panel-body">
                        <p>{{blog.description}}


                    </div>
                    <div class="panel-footer">
                        <blockquote class="blockquote mb-0">

                            <footer class="blockquote-footer"> Posted by {{blog.user.username}}</footer>
                        </blockquote>


                    </div>

                </div>

            </div>
            <!-- end of col9 -->
            <div class="col col-md-3">
                <div class="row">
                    <h5> <i class="fas fa-quote-left"></i> {{random.quote}} <i class="fas fa-quote-right"></i></h5>

                </div>

                <div class="row">
                    <h2>Add Comment<i class="fas fa-comment-alt-edit"></i></h2>
                    {{wtf.quick_form(form)}}

                </div>
                <div class="row">
                    <h3>Older Comments</h3>
                    {% if comments %}
                    {% for comment in comments%}
                    <div class="thumbnail">
                        <p>{{comment.description}} ~ {{comment.name}} </p>
                        {% if current_user.is_authenticated%}
                        <a href="{{url_for('main.delete_comment',blog_id = blog.id)}}">Delete</a>
                        {% endif %}

                        {% endfor%}
                        {% else %}
                        <p>There are no comments</p>
                        {% endif %}
                    </div>


                </div>

            </div>
            <!-- end of col3 -->

        </div>

    </div>

    {% endblock%}
</body>

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
<!--{% import 'macros.html' as macro%}-->


<!-- Styles block -->

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


{% endblock %}
<!-- Content block -->


<!-- Content block -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="jumbotron">
            <div class="row font">
                <h5> <i class="fas fa-quote-left"></i> {{random.quote}} <i class="fas fa-quote-right"></i></h5>


            </div>


        </div>

    </div>

</div>


{% endblock%}

app/templates/macros.html
{% macro displayPost(blog_list) %}
<div class="row">
    {% if blog_list %}
    {% for blog in blog_list %}
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">{{blog.title}}</div>
            <div class="panel-body">{{blog.description}}
                <blockquote class="blockquote mb-0">
                    <h2></h2>
                    <footer class="blockquote-footer"> Posted by {{blog.user.username}}</footer>
                </blockquote>
            </div>
            <div class="panel-footer"><a href="{{url_for('main.new_comment',blog_id = category.id)}}"> Add a comment</a>

            </div>
        </div>

    </div>
    {% endfor %}
    {% else %}
    {% endif %}
</div>
{% endmacro %}



{% macro displayFullPost(blog_list) %}
<div class="row">
    {% if blog_list %}
    {% for blog in blog_list %}
    <div class="col-md-6">
        <div class="panel panel-danger">
            <div class="panel-heading">{{blog.title}}</div>
            <div class="panel-body">{{blog.description}}
                <blockquote class="blockquote mb-0">
                    <h2></h2>
                    <footer class="blockquote-footer"> Posted by {{blog.user.username}}</footer>
                </blockquote>
            </div>
            <div class="panel-footer"><a href="{{url_for('main.new_comment',blog_id = category.id)}}"> Add a comment</a>

            </div>
        </div>

    </div>
    {% endfor %}
    {% else %}
    {% endif %}
</div>
{% endmacro %}


{% macro displayComment(comments) %}
<ul>

    {% if comments %}
    {% for comment in comments %}
    <div class="row text-center">
        <a>
            <p style="color: brown">{{ comment.description }}</p>
        </a>
        <small> posted by {{comment.user.username}}</small>
    </div>
    {% endfor %}
    {% else %}

    <h3>No comments</h3>
    {%endif%}

</ul>


{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> MY BLOG </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}

                    <li style="color:white;padding:15px;">{{current_user.username}}</li>
                    <li><a href="/blogs/new/" class="navlink"> Write Blogs </a></li>
                    <li><a href="/posts" class="navlink"> View Blogs </a></li>


                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                    {%endif%}
                </ul>
        </div>

    </div>
</div>

app/templates/new.html
<body id="index">
    {% import 'bootstrap/wtf.html' as wtf %}
    {% extends 'bootstrap/base.html' %}
    {% include 'navbar.html'%}
    <!-- Styles block -->

    {% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    {% endblock %}


    <!-- Content block -->
    {% block content %}

    <div class="container">
        <div class="row story padded">
            <div class="col-md-6">
                <img src="/static/images/story.jpg" alt="New Blog Image">

            </div>
            <div class="col-md-6">
                {{wtf.quick_form(form)}}
            </div>

        </div>
    </div>


    {% endblock%}
</body>

app/templates/posts.html
<body>
    {% extends "base.html" %}
    {% import "bootstrap/wtf.html" as wtf%}

    <!-- Styles block -->

    {% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    {% endblock %}


    {% block content%}

    <div class="container">
        <div class="row">
            <div class="row">

            </div>

        </div>
        <div class="row">
            {% for blog in blogs %}
            <div class="col col-md-4">
                <div class="panel panel_default">
                    <div class="panel-heading">
                        <h1 id="title">{{blog.title | truncate(20)}}</h1>
                        <hr>

                    </div>

                    <div class="panel-body">
                        <p>{{blog.description | truncate(50)}}<blockquote class="blockquote mb-0">

                                <footer class="blockquote-footer"> Posted by {{blog.username}}</footer>
                            </blockquote>



                    </div>
                    <div class="panel-footer">
                        <a href="{{url_for('main.view_blog',blog_id = blog.id)}}" class="btn">Read More <i
                                class="fas fa-arrow-right"></i></a>
                        {% if current_user.is_authenticated%}
                                                
                        <a href="{{url_for('main.delete',blog_id = blog.id)}}" class="btn">Delete <i
                                class="fas fa-trash-alt"></i></a>
                        <a href="{{url_for('main.update_blog',blog_id = blog.id)}}" class="btn">Update <i
                                class="fas fa-edit"></i></a>
                        {% endif %}


                    </div>
                    

                </div>

            </div>
            {% endfor%}


        </div>

    </div>

    {% endblock%}
</body>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {%endif%}
        </div>
    </div>
</div>



<style>
    .img {
        border-radius: 40%;
    }
</style>


{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}